/**
 * Upload media
 *
 * Adds the js required to add a media upload button
 *
 * @package          Fat Frog Options
 * @license          license.txt
 * @copyright        2014 Fat Frog Themes
 * @since            1.0.0
 *
 * Please do not edit this file. This file is part of the Fat Frog Options Framework and all modifications
 * should be made in a child theme.
 */

(function ($) {

    var file_frame;

    $('.fatfrog-icon-widget-upload-image-button').live('click', function( event ){

        event.preventDefault();

        jQuery.data(document.body, 'prevElement', $(this).prev());

        // If the media frame already exists, reopen it.
        if ( file_frame ) {
            file_frame.open();
            return;
        }

        // Create the media frame.
        file_frame = wp.media.frames.file_frame = wp.media({
            title: $( this ).data( 'uploader_title' ),
            multiple: false  // Set to true to allow multiple files to be selected
        });

        // When an image is selected, run a callback.
        file_frame.on( 'select', function() {
            var inputUrl = jQuery.data(document.body, 'prevElement');
            // We set multiple to false so only get one image from the uploader
            attachment = file_frame.state().get('selection').first().toJSON();

            // Do something with attachment.id and/or attachment.url here
            inputUrl.val(attachment.url);
        });

        // Finally, open the modal
        file_frame.open();
    });

})(jQuery);